
GET http://localhost:8000/auth/login

//posting a user
###

POST  http://localhost:8000/auth/register
Content-Type: application/json

{
    "userId": 1,
    "username": "poline",
    "password": "pass",
    "role": "admin"
}

//posting a user
###
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
    "userId": 3,
    "username": "poly",
    "password": "pass1",
    "role": "user"
}


###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "jane",
  "password": "pass"
}


//search cities with the "a" in their name
###

GET http://localhost:8000/search/cities?searchTerm=i


###

GET http://localhost:8000/categories
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjczNzA1fQ.Q_NHytTrHzyYM_vuyTpDVzbWX20HTVIpFJ55R-toTqA


###

POST http://localhost:8000/restaurants
Content-Type: application/json

{
  "name": "The Zod Res",
  "streetAddress": "123 Main St",
  "zipCode": "12345",
  "cityId": 1
}
###
GET http://localhost:8000/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjczNzA1fQ.Q_NHytTrHzyYM_vuyTpDVzbWX20HTVIpFJ55R-toTqA
###


###
POST http://localhost:8000/comments
Content-Type: application/json

{
  "orderId": 123,
  "userId": 1,
  "commentText": "The delivery was slow but the food was delicious!",
  "isComplaint": false,
  "isPraise": true
}

###

PUT http://localhost:8000/states/4
Content-Type: application/json

{
    "name": "Uganda",
    "code":"UG"
}



###

GET http://localhost:8000/users/1

###
// Service to fetch the status of a particular order by order ID
GET http://localhost:8000/orderStatus/3/status
###

GET http://localhost:8000/states/4/cities/3/restaurants


###

//getting a category with letter n
GET http://localhost:8000/search/categories?searchTerm=n

###
// Service to fetch the owner of a restaurant by restaurant ID
GET http://localhost:8000/api/restaurants/21/owner

###
// fetch all restaurants owned by a particular user
GET http://localhost:8000/restaurantOwner/1/restaurants

###

POST  https://poline-api.azurewebsites.net/auth/login
Content-Type: application/json

{
    "username": "poly",
    "password": "pass1"
}

###

POST  http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "jane",
    "password": "pass"
}

###
POST https://poline-api.azurewebsites.net/auth/login
Content-Type: application/json

{
    "username": "poline",
    "password": "pass1"
}


//my services



//getting all cities in state with state id 2
###
GET http://localhost:8000/state/2/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjczNzA1fQ.Q_NHytTrHzyYM_vuyTpDVzbWX20HTVIpFJ55R-toTqA

###
// Service to fetch menu items by restaurant ID

GET http://localhost:8000/restaurants/1/menu_items

###
//getting the city by searching  with the two letters ke
GET http://localhost:8000/search/cities?searchTerm=ke

###


// service getting while  searching for categories that contain the term "di".
GET http://localhost:8000/search/categories?searchTerm=di


###
// tring to find a restaurant  restaurants owned by the restaurant owner with ID 1
GET http://localhost:8000/restaurantOwner/2/restaurants
###

//get the order information for the user with ID 2
GET http://localhost:8000/users/2/order

###
// Service to fetch the owner of a restaurant by restaurant ID + checling authorization 
GET http://localhost:8000/api/restaurants/21/owner
uthorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjczNzA1fQ.Q_NHytTrHzyYM_vuyTpDVzbWX20HTVIpFJ55R-toTqA

//end of services

###
//getting all the users


###

POST http://localhost:8000/orders
Content-Type: application/json

{
  "restaurantId": 5,
  "estimatedDeliveryTime": "2024-06-09T19:30:00Z",
  "deliveryAddressId": 1,
  "userId": 2,
  "price": 50.00,
  "discount": 5.00,
  "finalPrice": 45.00,
  "comment": "Please dont leave without signing out."
}
###
DELETE http://localhost:8000/menuItem/2

###

PUT http://localhost:8000/cities/2
Content-Type: application/json

{
    "name": "kenya",
    "code": "KE"
}




###
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
    "userId": 3,
    "username": "poly",
    "password": "pass1",
    "role": "user"
}
//login as a user

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "poly",
  "password": "pass1"
}

//only admins can get the users
###
GET http://localhost:8000/search/users?searchTerm=ne
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1MDc1fQ.OEs72NzWW9N4xAxAzffD5W0uVCMYq9v6VM6xlgl6XAI


//only admins can delete a user
###
DELETE http://localhost:8000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1MDc1fQ.OEs72NzWW9N4xAxAzffD5W0uVCMYq9v6VM6xlgl6XAI
###
//

//only admins can post an address
POST http://localhost:8000/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1MDc1fQ.OEs72NzWW9N4xAxAzffD5W0uVCMYq9v6VM6xlgl6XAI
Content-Type: application/json

{
  "streetAddress1": "123 Main St",
  "streetAddress2": "Apt 4B",
  "zipCode": "12345",
  "deliveryInstructions": "don't leave without signing the clock out",
  "userId": 2,
  "cityId": 3
}


//getting address with admin token
###
GET http://localhost:8000/address
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1MDc1fQ.OEs72NzWW9N4xAxAzffD5W0uVCMYq9v6VM6xlgl6XAI


//only admins can delete all cities
###
GET http://localhost:8000/states/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjczNzA1fQ.Q_NHytTrHzyYM_vuyTpDVzbWX20HTVIpFJ55R-toTqA


//only admins can delete orders
###
DELETE  http://localhost:8000/orders/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1MDc1fQ.OEs72NzWW9N4xAxAzffD5W0uVCMYq9v6VM6xlgl6XAI
 


 
//relationship
###
GET  http://localhost:8000/users/userorder/2

